export const USER_PROFILE_UPDATE_AVATAR = 'USER_PROFILE_UPDATE_AVATAR';
export const USER_PROFILE_UPDATE_POSTS = 'USER_PROFILE_UPDATE_POSTS';
export const USER_PROFILE_UPDATE_PHOTOS = 'USER_PROFILE_UPDATE_PHOTOS';
